[opener]
edit = [
	{ run = "${EDITOR:-vi} %s", desc = "$EDITOR",      for = "unix", block = true },
	{ run = "sudoedit %s",      desc = "sudoedit",     for = "unix", block = true },
	{ run = "code %s",          desc = "code",         for = "windows", orphan = true },
	{ run = "code -w %s",       desc = "code (block)", for = "windows", block = true },
]
